#!/usr/bin/env sh

# Configure your user to execute `yabai --load-sa` as the root user without having to enter a password.
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# Check the display size (e.g., grab the resolution here)
display_info=$(system_profiler SPDisplaysDataType | grep Resolution)

# If the resolution is 6016 x 3384 I want to apply bigger paddings
# This means I'm connected to my 55 inch tv
# The * are used as wildcards
if [[ "$display_info" == *"6016 x 3384"* ]]; then
	yabai -m config top_padding 400
	yabai -m config bottom_padding 300
	yabai -m config left_padding 1500
	yabai -m config right_padding 12
else
	# settings for other machines
	yabai -m config top_padding 0
	yabai -m config bottom_padding 0
	yabai -m config left_padding 0
	yabai -m config right_padding 0
fi

# Make the below apps transparent
app_list="^(Alacritty|System Settings|Raycast|Spotify)$"
# When my list of apps gains focus, make all background windows completely transparent
yabai -m signal --add event=window_focused app="$app_list" action="yabai -m config active_window_opacity 0.85"
yabai -m signal --add event=window_focused app="$app_list" action="yabai -m config normal_window_opacity 0.00001"
# yabai -m signal --add event=window_focused app="$mgmt_excluded_apps" action="yabai -m config normal_window_opacity 1.0"

# When any other app gains focus, reset both active and background window opacity to fully visible
yabai -m signal --add event=window_focused app!="$app_list" action="yabai -m config active_window_opacity 1.0"
yabai -m signal --add event=window_focused app!="$app_list" action="yabai -m config normal_window_opacity 1.0"

# make the apps below fully opaque (not transparent) so theyre always shown
# IF THE APP WAS CLOSED, OPEN IT, AND RESTART YABAI FOR THIS TO TAKE EFFECT, otherwise can't get it's ID
# All the options can be seen using 'man yabai'
always_shown_apps=("iStat Menus" "CleanShot X" "Calculator" "Hammerspoon" "BetterDisplay")
for app in "${always_shown_apps[@]}"; do
  # get the window ID for the app
  window_ids=$(yabai -m query --windows | jq -r --arg APP "$app" '.[] | select(.app == $APP) | .id')
  for id in $window_ids; do
    # set the opacity for that specific window
    yabai -m window "$id" --opacity 1.0
  done
done

# Exclude the following apps from window management
# Convert always_shown_apps to regex string for yabai rules
mgmt_excluded_apps="^($(IFS="|"; echo "${always_shown_apps[*]}"))$"
yabai -m rule --add app="$mgmt_excluded_apps" manage=off

# Uncomment these 2 lines if you want to use different excluded apps
# Comment the lines above
# mgmt_excluded_apps="^(Notes|iStat Menus|CleanShot X|Udemy Business)$"
# yabai -m rule --add app="$mgmt_excluded_apps" manage=off

# # In case you want to debug and see the contents of the variable
# echo "mgmt_excluded_apps: $mgmt_excluded_apps" >> /tmp/yabai_debug.log

# global settings
yabai -m config \
	mouse_follows_focus off \
	focus_follows_mouse off \
	window_origin_display default \
	window_placement second_child \
	window_zoom_persist on \
	window_topmost off \
	window_shadow off \
	window_animation_duration 2 \
	window_animation_frame_rate 120 \
	window_opacity_duration 0.0 \
	window_opacity on \
	insert_feedback_color 0xffd75f5f \
	active_window_border_color 0xff775759 \
	normal_window_border_color 0xff555555 \
	window_border_width 4 \
	window_border_radius 12 \
	window_border_blur off \
	window_border_hidpi on \
	window_border off \
	split_ratio 0.50 \
	split_type auto \
	auto_balance off \
	window_gap 06 \
	layout stack \
	mouse_modifier fn \
	mouse_action1 move \
	mouse_action2 resize \
	mouse_drop_action swap

echo "yabai configuration loaded.."
