# /Users/krishna/github/dotfiles-public/brew/10-essential/Brewfile
# https://github.com/linkarzu/dotfiles-public/blob/main/brew/10-essential/Brewfile

# Best editor of all times Neovim
# I'll install the following fonts from neovim script
# tap "homebrew/cask-fonts"
# cask "font-meslo-lg-nerd-font"
brew "neovim"
brew "gnu-sed"
# This one errors out, so install it from nvim script
# brew "jesseduffield/lazygit/lazygit"
brew "ripgrep"
brew "fd"
# Used to check if specific font packages are installed
brew "fontconfig"

###############################################################################

brew "bind"
brew "helm"
brew "jq"
brew "kubernetes-cli"
brew "mysql-client"
cask "raindropio"
cask "cursorcerer"
